#!/bin/sh

FLAGS=""
if [ ! -z "${PLUGIN_DEPTH}" ]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

# If PR clone strategy is cloning only the source branch
if [ "$PLUGIN_PR_CLONE_STRATEGY" = "SourceBranch" ]; then
	set -e
	set -x

	git fetch ${FLAGS} origin ${DRONE_COMMIT_REF}:
	git checkout ${DRONE_COMMIT_SHA} -b ${DRONE_SOURCE_BRANCH}
	exit 0
fi

# PR clone strategy is merge commit

targetRef=${DRONE_COMMIT_BRANCH}
if [ ! -z "${DRONE_COMMIT_BEFORE}" ]; then
	targetRef="${DRONE_COMMIT_BEFORE} -b ${DRONE_COMMIT_BRANCH}"
fi


set -e
set -x

git fetch ${FLAGS} origin +refs/heads/${DRONE_COMMIT_BRANCH}:

if [ "$DRONE_PR_MERGE_STRATEGY_BRANCH" = "true" ]; then
  git checkout -b ${DRONE_COMMIT_BRANCH} origin/${DRONE_COMMIT_BRANCH}
else
  git checkout ${targetRef}
fi

git fetch origin ${DRONE_COMMIT_REF}:
git merge ${DRONE_COMMIT_SHA}
