#!/bin/sh

FLAGS="--no-tags"
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="${FLAGS} --depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	set -x
	git init
	git remote add origin ${DRONE_REMOTE_URL}
	set +x
fi

# If PR clone strategy is cloning only the source branch
if [ "$PLUGIN_PR_CLONE_STRATEGY" == "SourceBranch" ]; then
	set -e
	set -x

	git fetch ${FLAGS} origin ${DRONE_COMMIT_REF}:
	git checkout ${DRONE_COMMIT_SHA} -b ${DRONE_SOURCE_BRANCH}
	exit 0
fi

# PR clone strategy is merge commit

targetRef=${DRONE_COMMIT_BRANCH}
if [[ ! -z "${DRONE_COMMIT_BEFORE}" ]]; then
	targetRef="${DRONE_COMMIT_BEFORE} -b ${DRONE_COMMIT_BRANCH}"
fi


set -e
set -x

git fetch ${FLAGS} origin +refs/heads/${DRONE_COMMIT_BRANCH}:
git checkout ${targetRef}

git fetch --no-tags origin ${DRONE_COMMIT_REF}:
git merge ${DRONE_COMMIT_SHA}
