#!/bin/sh

FLAGS=""
if [ ! -z "${PLUGIN_DEPTH}" ]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	set -x
	git init
	git config --global --add safe.directory '*'
	git remote add origin ${DRONE_REMOTE_URL}
	set +x
fi

if [ -n "$HARNESS_HTTP_PROXY" ] && [ -n "$HARNESS_HTTPS_PROXY" ]; then
  set -x
  git config --global http.proxy "$HARNESS_HTTP_PROXY"
  git config --global https.proxy "$HARNESS_HTTPS_PROXY"
  set +x
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/tags/${DRONE_TAG}:
git checkout -qf FETCH_HEAD
