#!/bin/sh

FLAGS="--no-tags"
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="${FLAGS} --depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	set -x
	git init
	git remote add origin ${DRONE_REMOTE_URL}
	set +x
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/tags/${DRONE_TAG}:
git checkout -qf FETCH_HEAD
