FROM redhat/ubi8-minimal:8.5
RUN microdnf install ca-certificates git git-lfs openssh curl perl python38 shadow-utils
RUN pip-3 install awscli

ADD posix/* /usr/local/bin/
RUN chmod -R 777 /etc/ssh
RUN groupadd drone && adduser -g drone -s /bin/sh -u 1000 drone
# RUN echo 'drone ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/drone
USER drone:drone
RUN chmod -R 777 /home/drone

ENTRYPOINT ["/usr/local/bin/clone"]
