FROM redhat/ubi8/ubi-minimal:8.5-240.1648458092
RUN microdnf update && microdnf install ca-certificates git git-lfs openssh curl perl python38 shadow-utils
RUN pip-3 install awscli

ADD posix/* /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/clone"] 
