# escape=`

FROM mcr.microsoft.com/windows/servercore:1903 AS git
SHELL ["powershell.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; `
    Invoke-WebRequest -UseBasicParsing https://github.com/git-for-windows/git/releases/download/v2.39.2.windows.1/MinGit-2.39.2-64-bit.zip -OutFile git.zip; `
    Expand-Archive git.zip -DestinationPath C:\git;

# Download and extract Git LFS (Updated to v3.7.0)
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; `
    Invoke-WebRequest -UseBasicParsing https://github.com/git-lfs/git-lfs/releases/download/v3.7.0/git-lfs-windows-amd64-v3.7.0.zip -OutFile git-lfs.zip; `
    Expand-Archive git-lfs.zip -DestinationPath C:\git-lfs;

FROM mcr.microsoft.com/powershell:nanoserver-1903
COPY --from=git /git /git
COPY --from=git /git-lfs /git-lfs


# https://github.com/PowerShell/PowerShell/issues/6211#issuecomment-367477137
USER ContainerAdministrator
RUN setx /M PATH "%PATH%;C:\Program Files\PowerShell;C:\git-lfs\git-lfs-3.7.0"


# Add enhanced binary with embedded scc and telemetry (Windows)
# The binary embeds all windows scripts, so we don't need to copy them separately
COPY release/windows/amd64/drone-git.exe /bin/drone-git.exe

# Create wrapper script that calls the enhanced binary for backward compatibility
RUN powershell -Command "Set-Content -Path 'C:\bin\clone.ps1' -Value '& C:\bin\drone-git.exe @args'"
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
# Use old entrypoint for backward compatibility (now calls enhanced binary)
CMD ["pwsh", "C:\\bin\\clone.ps1"]
