FROM arm32v6/alpine:3.20
RUN apk add --no-cache ca-certificates git git-lfs openssh curl perl aws-cli sudo

ADD posix/* /usr/local/bin/
RUN chmod -R 777 /etc/ssh

# Remove unnecessary SSL keys
RUN rm -rf /usr/share/doc/perl-IO-Socket-SSL \
          /usr/share/doc/perl-Net-SSLeay/examples/server_key.pem \
          /usr/local/lib/python3.8/site-packages/awscli/examples
          /usr/local/lib/python3.6/site-packages/botocore/data/sts/2011-06-15/examples-1.json \
          /usr/local/lib/python3.6/site-packages/botocore/data/iam/2010-05-08/examples-1.json \
          /usr/local/lib/python3.8/site-packages/botocore/data/iam/2010-05-08/examples-1.json \
          /usr/local/lib/python3.8/site-packages/botocore/data/sts/2011-06-15/examples-1.json \
          /usr/local/lib/python3.8/site-packages/awscli/topics


RUN adduser -g Drone -s /bin/sh -D -u 1000 drone
RUN echo 'drone ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/drone
USER drone:drone
RUN chmod -R 777 /home/drone

ENTRYPOINT ["/usr/local/bin/clone-retry-wrapper"]
