FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5-240.1648458092
RUN microdnf update && microdnf install git ca-certificates shadow-utils \
    && rm -rf /var/cache/yum \
    && microdnf clean all

ADD posix/* /usr/local/bin/

RUN chmod -R 777 /etc/ssh
RUN groupadd drone
RUN adduser -g drone -s /bin/sh -u 1000 drone
USER drone:drone
RUN chmod -R 777 /home/drone

ENTRYPOINT ["/usr/local/bin/clone"]
